spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://192.168.98.1:3306/jacob-aide?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: aide
    password: jacob-aide
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: assistant
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
