telegram:
  bot:
    token: ENC(aodn+RjSDgSTUAdMQj44Rek15QKRJ4aTmgGxZub3nj9XI6bDVVyiOFrD1iulfPA1W1aCTXbA56w=)
    name: ENC(kQfyQx23nwQmcx8txEyZtQa6dK8bI/ww9fz1JFdgH10=)
    proxy:
      type: SOCKS5
      host: 192.168.98.1
      port: 10808


logging:
  level:
    root: INFO

